// Display list for UI (alphabetically sorted)
export const BROKER_NAMES = [
  'Abalta',
  'AdDefend',
  'AdElement',
  'Adsquare',
  'Arkeero',
  'BidSwitch',
  'Bliss Point Media',
  'Bookyourdata',
  'Censia',
  'Cint',
  'Comscore',
  'Confiant',
  'Connext Digital',
  'Cybba',
  'Dice',
  'Diligent',
  'Entelo',
  'EproDirect',
  'Ermes',
  'Exactag',
  'Fetcher',
  'Fifty',
  'Findmypast',
  'FourLeafDatra',
  'FullContact',
  'GADSME',
  'GfK',
  'Growbots',
  'ID5',
  'IntentMacro',
  'Intalytics',
  'Liveintent',
  'MaxMind',
  'MediaSoft',
  'Milestone Marketing Solutions',
  'Optimal Fusion',
  'PacificEast',
  'PitchBook',
  'Pop Acta Media',
  'PubMatric',
  'PushHint',
  'RecruitBot',
  'RocketReach',
  'SalesIntel',
  'Shopalyst',
  'Smart Traffik',
  'Smartology',
  'Sonobi',
  'Spokeo',
  'SwordFish',
  'Sync.me',
  'Tech target',
  'True Influence',
  'UpLead',
  'VenPath',
  'VUUKLE',
  'W20',
  'Yansi',
].sort();
